[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@seda-protocol/evm/=lib/seda-evm-contracts/"
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }

[rpc_endpoints]
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"
gnosisChiado = "https://rpc.chiadochain.net"
superseedSepolia = "https://sepolia.superseed.xyz"
hyperliquidPurrsec = "https://rpc.hyperliquid-testnet.xyz/evm"
